### ISSUE TITLE
Zero-valued limit parameter returns X-Next header

### ISSUE THREAD

**Issue by jbouwman** [threatgrid/ctia#1066]
Calling a search endpoint with a limit value of zero returns an X-Next header that can lead naive result scrollers to recurse. 

For instance:

    https://private.intel.test.iroh.site/ctia/incident/search?limit=0&offset=0

returns the header:

    x-next: limit=0&offset=0

**Comment by ereteog** [comment]
I agree with the conclusion on naive scrollers, but the header still true with respect to the search result.
A CTIA client has the necessary information (the original request and the response header) to not recur here.
Which header would you expect in such a case?
