### ISSUE TITLE
Refactor the way that auth :capabilities work

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#108]
I think the implementation for capabilities isn't quite right.  Currently you have to have just one of the capabilities defined for a route to be able to use the route.  Typically there is a user level capability and an admin capability, as in...

:capabilities #{:create-judgement :admin}

I think that :admin should be implicit, and we should be able to require all of the capabilities before granting access.  That way we could protect routes that use multiple stores with just the capabilities to read those stores.  The user would need to have all of the capabilities required by the compound data route.  This way we could reduce the number of permission grants that we give by not having as many :list-thing-A-by-thing-B style permissions.

Need to get more input on this idea.

**Comment by craigbro** [comment]
Hmm, my concern with :admin is that it's a role with a set of capabilities.  I would not want to have a magical role, but would like them to be explicitly defined.
