### ISSUE TITLE
Support STIX 1.2 data format

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#123]
# Support STIX 1.2 data format in our API

Use the java-stix lib and don't worry about swagger UI compatibility.

Here is my high-level TODO list:
- [x] Export a single Indicator
- [ ] Import a single Indicator
- [ ] Export judgements for an indicator
- [ ] Test importing real-world TAXI data

**Comment by craigbro** [comment]
I think it should return the original representation of the indicator, without any judgements at `/cia/indicators/ID`  See my coments on 142 regarding how we should represent imported XML indicators as a direct JSON repreentation of XML.

I think we should have the export of an indicator in a form that is just the judgements rendered into a simple observable pattern at: `/cia/indiator/ID/judgements  and use the same filter map logic

**Comment by polygloton** [comment]
See also #146.
