### ISSUE TITLE
Indicator :version schema should be string

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#132]
Currently it is integer, which is a mistake.  This is the XML schema for STIX:

```xml
	<xs:simpleType name="IndicatorVersionType">
		<xs:annotation>
			<xs:documentation>An enumeration of all versions of the Indicator type valid in the current release of STIX.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="2.0"/>
			<xs:enumeration value="2.0.1"/>
			<xs:enumeration value="2.1" />
			<xs:enumeration value="2.1.1" />
			<xs:enumeration value="2.2" />
		</xs:restriction>
	</xs:simpleType>
```

The java-stix library has it as a string.  String would be more flexible for non-STIX values.

**Comment by quoll** [comment]
Where is this set to an integer? The schema in CTIM has a string. Are you referring to another part of the code?

**Comment by yogsototh** [comment]
I believe it was fixed by https://github.com/threatgrid/ctia/pull/322
