### ISSUE TITLE
Do we need a way to "close a judgement" by setting it's valid_time.end

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#135]
The investigate API provides history of when a domain was tagged/categorized.

https://investigate-api.readme.io/docs/domain-tagging-dates-for-a-domain

That brings up some interesting issues around how we would represent their judgements
since we do not allow judgement modification, you can't change the valid_time of it
It seems to me that we may need to allow someone to "close" a judgement
or otherwise set the valid_time end date

Otherwise, we end up them having to make a series of short lifespan judgements, which means more volume/velocity moving thru CIA and more noise.  Or they have to deactivate/delete the judgement previous judgement.

Either of these solutions means that we need to provide sources with a way of querying their judgements, we don't want them to have to "remember" which ones thry made so they can redact them.

Hmm, it's starting to feel like the notion of Judgements being immutable is getting dirty.

**Comment by craigbro** [comment]
I think we do need this.

**Comment by polygloton** [comment]
Maybe we need a way to set capabilities at a field level (currently it is just API level).

**Comment by craigbro** [comment]
Stephen Sloan <notifications@github.com> writes:

> Maybe we need a way to set capabilities at a field level (currently it
> is just API level).

I think it's a specific action, with it's own Event type actually.

-- 
Craig Brozefsky
Principal Engineer, AMP Threat Grid
Cisco Security Business Group
+1-773-469-8349
