### ISSUE TITLE
Incident's created-time

### ISSUE THREAD

**Issue by agzam** [threatgrid/ctia#1366]
We have these public fields in the Incident:

```
:incident_time.opened
:incident_time.discovered
:incident_time.reported
:incident_time.remediated
:incident_time.closed
:incident_time.rejected
```

Turns out, we also need to expose `created` field as well.

Related discussion: https://github.com/advthreat/iroh/issues/7853#issuecomment-1540591124

**Comment by ereteog** [comment]
please opens issues in IROH.

**Comment by agzam** [comment]
https://github.com/advthreat/iroh/issues/7866
