### ISSUE TITLE
READ access request for the XDR QA team

### ISSUE THREAD

**Issue by hshahman** [threatgrid/ctia#1381]
From time-to-time we get tickets that are referenced to issues/PRs in CTIA repository, to see the content of those issues/PRs QA team needs read access to CTIA repo. 
Integrations repository contains use cases and technical details that help the QA team to get more familiar with what needs to be tested and how each integration works. Read access to that repository is needed as well.

Could you please create a new team, called "XDR QA", and provide **Read access only** to [CTIA](https://github.com/threatgrid/ctia) and [3rd party integrations](https://github.com/threatgrid/integrations/) repositories?

### Here is list of XDR QA team members:
Houman Shahmansouri (hshahman)
Abhishek Dubey (abhidub2)
Jason Busboom (jbusboom)
James Moser (jamoser)
Neel Kamal (neelkam)
Andrii Zadumin (azadumin)
Hisan Mohamed Saleeth (mohomoha)
Jagruti Patil (jagrutpa)
Krithika Selvavinayagam (kriths)
Maksym Bielyshev (mbielysh)
Patricia Collier (trcollie)
Samira Azimi (saazimi)
Sundeep Kaur (sundkaur)

**Comment by ereteog** [comment]
CTIA is open source, then everyone has a read access :-)
BTW, since it's open source, we avoid opening issues here (response or IROH).

**Comment by miwhitle** [comment]
Thanks @ereteog!

**Comment by miwhitle** [comment]
Received approval from Ian via chat. 

<img width="1107" alt="Screenshot 2023-08-03 at 2 29 39 PM" src="https://github.com/threatgrid/ctia/assets/40034966/077f15b7-53bf-4f59-ad6b-6f35808a7de7">

**Comment by miwhitle** [comment]
Created the XDR QA team and added the two requested repos.
