### ISSUE TITLE
Remove Joda Time from Schema

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#140]
Joda Time is deprecated and users are recommended to switch to the java.time (JSR-310) utility in Java SE 8+  However, we don't want to limit our app to only running in Java 8 environments, so we're going to move toward using java.util.Date.

It also makes our schemas not portable to cljs, and it breaks serialization in yml and other formats.  It also prevents me from using enduro for file-based atom durability.

Edit: I originally suggested we use https://docs.oracle.com/javase/8/docs/api/java/time/OffsetTime.html
More info about JSR-310 date and time improvements:
http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html  The team discussed this option and decided against it.

Edit: Use java.util.Date instead of java.time or joda DateTime.  For the schema use schema.core/Inst instead of defining a specific type since schema will use the desired type depending on environment.

**Comment by polygloton** [comment]
Remaining to-dos:

 - [ ] Refactor to avoid joda as intermediary in coercion
 - [ ] Update the datastructures.md documentation (it references joda)
