### ISSUE TITLE
Capture observable qualifier data

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#142]
There are some fields on Cybox observable (which is polymorphic) that we don't currently capture.  Should we capture any of these?  Address is probably the most interesting.
## Address (ip, ipv6, device)
- [ ] is destination?
- [ ] is source?
- [ ] is spoofed?

See http://cybox.mitre.org/language/version2.1/xsddocs/objects/Address_Object.html
## Domain
- [ ] Type (FQDN, TLD)

See http://cybox.mitre.org/language/version2.1/xsddocs/objects/Domain_Name_Object.html
## User
- [ ] password required?
- [ ] a bunch of account detail fields the we probably don't care about

See http://cybox.mitre.org/language/version2.1/xsddocs/objects/User_Account_Object.html
## File (sha256, sha1, md5)
- [ ] A bunch of fields for files that we probably don't care about

See http://cybox.mitre.org/language/version2.1/xsddocs/objects/File_Object.html

**Comment by craigbro** [comment]
Perhaps we can add a "qualifier" field to the observable object.  it does not playa  role as a key, but after a verdict hit, it can be used to check if it applies to the observable based on where you got it from?
