### ISSUE TITLE
Design ID formats that are more than just randm UUIDs

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#16]
We should investigate whether having a semantically meaningful ID is worth doing.

The advantage is that just the ID reveals something about the entity, but it can also dedupe semantically identical entities that we get via different channels - avoiding constant deduplication.

For example, judgements could be: source-type-timestamp

So if we got the same judgement via different channels, we would not store it more than once.

**Comment by polygloton** [comment]
I'm closing this since we are having a lot of discussions about using a new ID standard.
