### ISSUE TITLE
Race condition in events_test.clj

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#161]
I intermittently get the following test failure from master:

lein test :only ctia.events-test/test-recents

FAIL in (test-recents) (events_test.clj:76)
expected: (= ["1" "2" "3"] (map (comp :id :model) (recent-events)))
  actual: (not (= ["1" "2" "3"] ()))

I think there's a race condition on that line.

**Comment by polygloton** [comment]
Should be fixed, but since it is an intermittent failure, we should wait a few days and get confirmation that we aren't seeing this anymore.

**Comment by polygloton** [comment]
Seems to be resolved.
