### ISSUE TITLE
The /version should include the commit number of the build.

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#177]
When I ask for the version, I should get the release number, as well as the build number (the commit ID).

**Comment by polygloton** [comment]
I think this is hard to do in git.  I used to to do this in SVN all the time though.  How about we set two properties: ctia.show.release and ctia.show.build.  For the build ID at least, we can have some default like "dev" or "alpha".  Then, for the Dockerfile build, we can have a shell command set those values using a git command(s).  Maybe the release number is just hard coded in the properties.

**Comment by charles-dyfis-net** [comment]
Not at all hard to do in git. Just as in svn the preferred/correct version is to delegate to a `svnversion` subcommand (using the CVS-alike `$Id$`-style replacement being a deprecated approach that requires properties to be enabled), `git describe` will do the job cleanly in a git repo properly using annotated tags.

**Comment by charles-dyfis-net** [comment]
...so, if you're properly tagging your releases, `git describe` will look at the tags; if you're on the revision 4.5.3, that's what you get as output; if you're one rev past it, then you might get something like `4.5.3-1-4eb512`, indicating that you're one rev past 4.5.3, and that the hash starts with `4eb`. (If not annotating your tags, may need to use `git describe --tags` for them to be honored).

**Comment by polygloton** [comment]
What does this look like in code?

**Comment by charles-dyfis-net** [comment]
So, a *typical* approach for a JVM-based project is to write the output of svnversion or git describe into a properties file that you bundle into your JAR. Maven has a plugin to automate that out-of-the-box; for ant, calling external commands is literally a `<task>`; for leiningen, though... hmm, good question -- last time I ran a Clojure project it was in a Maven shop, and ended up not actually using lein for build.

**Comment by charles-dyfis-net** [comment]
...a bit of quick googling finds someone else's implementation: https://github.com/cvillecsteele/lein-git-version

**Comment by AlexBaranosky** [comment]
@polygloton this is how face does it:
https://github.com/threatgrid/threatbrain/blob/master/src/threatbrain/face/build.clj

https://github.com/threatgrid/threatbrain/blob/master/project.clj#L159
