### ISSUE TITLE
Fix tests, fixtures and ES Store querying

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#188]
Since latest changes to Schemas and ES mappings, a lot of tests are failing, fix it

**Comment by craigbro** [comment]
Interestingly, they are failing with atom store and ES store.

**Comment by craigbro** [comment]
It's the smashing of nested objects to regular objects that I did.  I prefer non nested objects, especially for singletons.  It's arguable that when we have an array of observables, we would want to use nested obejcts so we can search for things be specific type.  However, I think I would prefer to do a mapping which produces a field that combines "type:value" so we can produce that term ourselves.

Using nested objects is quite expensive in ES and will slow our indexes down alot as they get larger.  It also sets an upper bound on the number of sub-elements we can have.
