### ISSUE TITLE
Typo on main page

### ISSUE THREAD

**Issue by paulgdavis** [threatgrid/ctia#194]
I think you are missing a "1"
--- snip ----
You will then need to tell your CTIA where to find it's dependencies. The services will be listening on your docker-machine's IP, which you can get with the command, docker-machine ip, and then you define your own resources/ctia.properties file with the following values:

ctia.store.default=es
ctia.store.es.uri=http://192.168.99.100:9200
ctia.producer.es.uri=http://**1**92.168.99.100:9200

--- snip ---

**Comment by polygloton** [comment]
Feel free to edit the README directly :)
