### ISSUE TITLE
Improve COA relationships

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#219]
Define COA "states"

- [ x] Suggested COA is a high-level/abstract recommendation
- [ ] Requested COA is specific and can can be executed
  - [x ] Uses OpenC2 specification
  - [ x] May have been a Suggested COA that was converted into a Requested COA
  - [ x] May link to a Suggested COA
- [ ] Taken COA is based on a Requested COA and adds logs, results, etc.
  - [  ] Define COAResult entity

# Suggested COAS

Adding a Relationship from an Incident to a COA, makes it a Suggested COA.  The COA can be one that already existed, or it could have been specifically generated for that Incident.

# Requested COAs

To Request a COA that has been Suggested, a Copy of the COA is made, and a `derived-from` relationship is made from the original COA to the new COA.  It's `state` is set to "requested" and a "requested" Relationship from the Incident to it is added.  Any Suggested COA relationship should be preserved.

# Taken COA

A Taken COA  is a Requested COA whose `state` is set to `taken` and may have a Relationship to a COAResult object.

**Comment by polygloton** [comment]
See also #178

**Comment by craigbro** [comment]
I will put together a PR witha  sketch for theis schema, and then we can collectively review.
