### ISSUE TITLE
Can search for indicators

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#220]
When a security operators want to insert an indicator into CTIA, they need to check if the indicator already exists.  Need sufficient indicator search capabilities in the API.

We already have a GET by title, but it must be an exact match.  Need, at minimum, a search by word in title.
- [ ] Search by title
- [x] Pagination of results (See #221)

**Comment by yogsototh** [comment]
I started to work on this one.
To be able to have more search routes, or maybe a route providing the ability to filter using multiple dimensions I'll certainly need the functionalities added in PR#241.

So should I focus on adding only one dimension search route, or if I can, should I provide a multi-dimension search?

**Comment by craigbro** [comment]
Only search by title, and it should be exact match, maybe substring match.

**Comment by craigbro** [comment]
Actually, is this not already covered by the "list" using "title" as a filter argument?

**Comment by yogsototh** [comment]
Actually in master we already expose a route to find indicators by title using only exact search.

**Comment by craigbro** [comment]
Ok, so I don't think we need somethign in between.

I think we need the existing "exact match" search which returns a list of matching indicators.

And then beyond that it's proper search.

An Analyst is going to have full search capability, something we would not be giving to all devices out there.

That said, I don't want "full search" to be part of Debutant release.
