### ISSUE TITLE
New dispostion_name in Judgements

### ISSUE THREAD

**Issue by deandebeer** [threatgrid/ctia#228]
Looking at Judgements...They hold observations with added meta data but we only allow for a disposition as related to a decision/judgement made about the observable. 

disposition_name (string) = ['Common', 'Unknown', 'Suspicious', 'Malicious', 'Clean'],

The addition of a string "interesting" should support the use case of a user wanting to add a observation that is informational or interesting in nature at the time of discovery but not malicious, unknown, clean, etc...

Would a disposition of 'interesting' participate in the verdict system? In our global instance we only want to alert on observations in Verdicts with a High Confidence. A user's local CTIA may be used to provide data to systems to hunt for interesting yet, potentially, unconfirmed observables.

**Comment by craigbro** [comment]
Does Suspicious already handle this?  Supsicious is kind a weasly disposition, implying "we think it's up to something but can't call it malicious"
