### ISSUE TITLE
Use only the URI for ES setup in properties

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#234]
Currently we have both a URI property, and two properties (one each for host and port), multiplied by two for the store and the producer.  If we could get by with just the URI, then let's use that.

**Comment by gbuisson** [comment]
It is totally doable
- REST uses a single http uri, 
- native uses pairs [[:ip :port]]
- native allows multiple hosts

we could transform the props value to extract the relevant parts for native, It won't be as explicit though.

**Comment by polygloton** [comment]
I can't help thinking we should stop supporting native mode.
