### ISSUE TITLE
Local logging abstraction

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#239]
As a developer, I want to log things like HTTP request/response.  To a log file or to the console is fine.  Should I use log4j?  Should I use the event logging facilities?

We need a clear abstraction for doing this logging, something like a ctia.lib.logging namespace.

**Comment by polygloton** [comment]
See also #24

**Comment by polygloton** [comment]
Is clojure.tools.logging enough for this?  Or do we want a logging facade that we can add functionality to?

**Comment by craigbro** [comment]
See threatbrain.face.sserver and it's logging namespace for examples of how to set that up.
