### ISSUE TITLE
A core.async listener which writes domain events to a log file.

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#24]
A listener which takes events from our core.async channel for domain events, and logs them to a log file.

**Comment by quoll** [comment]
My first inclination was to log this data at INFO level. Is that right? Do we make this configurable instead?

**Comment by quoll** [comment]
I think I'm ready to PR this, but tests pulled from central are failing. It looks like I might just need to have some services running to make these work?

**Comment by quoll** [comment]
This is done, but there is a new patch that builds on issue-23, and I'm waiting until that is complete before finishing this
