### ISSUE TITLE
Hooks are configured in properties

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#242]
Currently they are configured in project.clj.

- [x] Default hooks are defined in code
- [x] Additional hooks may be provided on the class path (eg "java -jar ... -cp ...")
- [x] Additional hooks are enabled in properties or ENV vars

**Comment by polygloton** [comment]
The proposed solution is to use a set of ordinal properties, hopefully infinitely large, something like "ctia.hook.1", "ctia.hook.2", ... "ctia.hook.N".  Then we would convert that into a vector.  It would complicate our properties code a bit, but we could handle it.

**Comment by craigbro** [comment]
I prefer the use of a single property, a comma sep list of classes to load as hooks.
