### ISSUE TITLE
Can we remove the judgement severity field?

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#244]
To quote Craig, "Severity is like a vestigial tail -- not sure why it's included still."  :-)

**Comment by deandebeer** [comment]
What is the reasoning for removing severity?

**Comment by craigbro** [comment]
It's a 0-100 scale, which we don't use in other places as a generic value.

To quote from that same email:

There is no notion of "threat score" in Judgements, there is Severity
and Confidence.  Confidence is a enum (High, Medium, Low).  Severity is
a 0-100, but that's not really a place to put score.  Not all judgements
are going to be scored by a sandbox or other mechanism like that.
Severity is like a vestigial tail -- not sure why it's included still.

A score only means something when it includes a scale, which means that
the client needs to know the source.  Aka, t's just a number that's
meaning varies from source to source.  the "disposition" is what we are
already using as our accepted universal "threat level" so adding yet
another universal decimal scale value?  Not sure it's needed.

**Comment by deandebeer** [comment]
Severity should be treated the same as confidence then, no?

Low, medium, high, critical.

Disposition represents a decision around the nature of the observable in the context of the device or user creating the record. If disposition is 'informational' that does not mean it cannot have a confidence and a severity assigned to it.

**Comment by craigbro** [comment]
Another way to put it, is that a judgement really is about the disposition and the confidence we have in it.

What we call Severity is probably better called Impact.  In STIX an Indicator would have a LikelyImpact, which includes a High/Medium/Low qualifier as well as a Description.

If we wanted to have a universally supported "Severity" in our Judgements, I do think calling it Impact is better, and it shoul dbe High/Medium/Low and not a numeric value.

**Comment by craigbro** [comment]
Oh, you beat me too it @deandebeer

**Comment by deandebeer** [comment]
I win! :)

Impact is more appropriate in this case, agreed.

**Comment by craigbro** [comment]
BTW, we should remember that Judgements are not ALL the information we have about the observable,and that they link to Indicators, which contain Impact already, and which also link to TTPs and other more detailed descriptions.

The intent of pushing any of these things down into Judgement, is really to allow for one of a few things:

  * Easy import of Threat Content (lists of bad IPs) where we don't have Indicator or other data
  * The minimal information a client/device needs to decide Yes/No without incurring the overhead of several API calls and parsing.
 

I think Confidence is certianly useful in the second case, and I think that a good argument could be made for Impact being equally useful (we call adware Low impact?)
