### ISSUE TITLE
A core.async listener that turnes Judgement domain events into new verdicts

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#25]
A process which listens for Judgements and ensures that a new verdict is generated for the observable.

**Comment by quoll** [comment]
My presumptions on this are that the process should listen to the Events core.async channel, filtering on Judgements. In terms of getting a verdict, from a Judgement, am I correct in presuming that this is via the calculate-verdict function on the IJudgementStore protocol?

**Comment by polygloton** [comment]
I think calculate judgements would move out of the store.  It would go into ctia.domain.verdicts, or something like that.  A new listener would get create judgment events, and it would insert verdicts into a new verdict store, and remove previous verdicts.  You would have to create the verdict store.
