### ISSUE TITLE
Refactor handler tests for generative testing

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#252]
In #251 we added some generative tests.  It needs some refactoring.

- [ ] Use defspec and forall in the tests so that we get failure reduction
- [ ] Add a new defspec-for-each-fixture type of macro, similar to the deftest one
- [ ] Make sure that we have enough coverage with these new tests
- [ ] If the tests are slow (which is likely with generative testing), then mark them with a :slow test selector that doesn't run by default

You might get inspiration from this code:

https://github.com/polygloton/ctia/blob/issue-169-spike/test/ctia/domain/id_test.clj

**Comment by yogsototh** [comment]
We might want to use `test.chuck` this way we could provide a TEST_CHECK_FACTOR in the CI to make more tests in the CI than in development environment.

**Comment by polygloton** [comment]
That is a good idea.  We can also use test selectors to avoid running the generative tests locally, since they tend to be very slow.  I've used :slow in the past.  Of course we still have the option of running the :slow tests locally before pushing.

**Comment by AlexBaranosky** [comment]
@polygloton I think it'd b better to have it run the generative tests less times, than have it not run them at all locally. Then have it run them with more samples on CI.
