### ISSUE TITLE
Where should we set permgen space?

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#263]
Currently we set it in project.clj in two places.  I think we can get away with only setting in the :ci profile, but if we need it at the top, then we should delete it in the :ci profile.

**Comment by craigbro** [comment]
Stephen Sloan <notifications@github.com> writes:

> Currently we set it in project.clj in two places. I think we can get
> away with only setting in the :ci profile, but if we need it at the
> top, then we should delete it in the :ci profile.
>

Set it at the top, if we're hitting permgen problems in CI, we will hit
them in dev.

-- 
Craig Brozefsky
Principal Engineer, AMP Threat Grid
Cisco Security Business Group
+1-773-469-8349
