### ISSUE TITLE
Generative tests should shrink

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#269]
We have generative tests that take, for example, 100 samples and then applies them to an expectation.  When there is test failure, however, that means that we get up to 100 test failure prints for each test (and there are several).  That sort of misses the point of test.check.  We need to take advantage of the features for shrinking tests failures to a single failure message.

See for example:
https://github.com/polygloton/ctia/blob/issue-169-spike/test/ctia/domain/id_test.clj

**Comment by yogsototh** [comment]
After taking a look, I believe that it might be difficult to code some tests using `defspec`.

For example,  in my generative tests I have often this structure:

1. generate a sequence of entities,
2. generate another sequence of entities depending on the first sequence,
3. generate another sequence depending of the two previous sequences...

Furthermore we use the `def-test-for-each-store` macro.
We would then have to make another `defspec-for-each-store` macro.

It might be a bit hard to rewrite this kind of tests directly.

So, I believe in a first time we could just use `reduced` to short circuit tests.
Stopping on the first failure will be an improvement.

~~~clojure
(deftest dummy-short-circuited-test
  (reduce
    (fn [_ i]
      (if (= i (+ i 1))
        (is (= i (+ i 1)))
        (reduced (is (= i (+ i 1))))))
    (range 100)))
~~~

This is far from perfect, but that could help to make test output clearer.

**Comment by polygloton** [comment]
I think the difficulty only exists because of the way you are using it.  We don't need anything so complicated.  I don't think it even make sense in the domain of our application.  Users won't behave like that.  It would be easier to just generate a sequence of things before you enter the for-all scope.

I feel like your example is trying to reinvent they way that test.check works, but does so without many of the standard benefits of test.check.  Generative testing with shrinking is great!  Let's use it.  Generate some API input and then make assertions on the output and on side effects (like events).  When the test fails, we get a small input that still fails.  

If the generated input isn't a good fit, remember that you get to write the generator.  For example, in the linked example above, I have a generator called gen-id-long-with-parts.  It generates an ID and also the parts that are expected to be the result of parsing the ID.  That way I'm able to make assertions on some code that parsed an ID.

**Comment by polygloton** [comment]
It looks like we are still adding tests that are generating data and looping over the samples, without allowing magnification to take place.  Here is an example that got merged into master today:

https://github.com/threatgrid/ctia/blob/8d3fc72c313f59a2a59329998eafe4bcfb00f80c/test/ctia/http/routes/observable_test.clj

When this test fails (as it is doing for me in my local branch), I see 100 error messages per failing test case.  This makes it very hard to diagnose what is failing.  I have to point out that there is an excellent alternative to the current approach (using generative testing with magnification), and I find the current approach very undesirable.  I don't want to have to parse thousands of test failures when something is wrong in my local development branch.  That is happening to me now, and has happened to me before on multiple occasions.  Please please please use minification if you are generating samples in tests; it works great, and its not very hard (just different).

**Comment by yogsototh** [comment]
Of course I tried to use a `defspec` instead of a `deftest` which generate thousand of errors.
But I had a difficulty because we should first create the equivalent of `deftest-for-each-store` which use fixtures in `defspec`. I believed it was beyond the scope of my PR.

Let's focus on #252 to have correct generative testing that don't generate thousand of error lines.
