### ISSUE TITLE
Kibana Dashboards

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#282]
# Good to have Dashboards for CTIA:
## Judgements

First, get TG feeds loaded up for several days, like, a whole month of data...
- date histogram (date histogram)
- breakdown by observable type (terms)
- breakdown by source/origin (terms)
- breakdown by confidence/impact/severity (terms)
- Top Indicators... (terms)
- Top Observable values (terms)
## Sighthings

Each TG Feed hit is also a Sighting, so we should import sighitngs as well
- date histogram (date histogram)
- breakdown by observable type (terms)
- breakdown by source/origin (terms)
- breakdown by confidence/impact/severity (terms)

The query bar can be used to limit to specific observable values...
## Indicators

Load TG indicators, dedupe on title please
- breakdown by confidence
- breakdown by origin/source (who made the indicator)
# Make Dashbaords Persistent

Once we have some dashboards defined, we need to work on a process for exporting them as json, and putting them on the Kibana service, and linking to them.  We CAn save to the ES instance, but we want to also have them as exported JSON so that they work on a brand new instance that doesn't have them saved to ES

**Comment by nrezvani** [comment]
Here is the first draft of the [CTIA statistics dashboard](http://alpha.ctia.threatgrid.com/app/kibana#/dashboard/CTIA-Statistics). I'll add more graphs to it once we have more data.

**Comment by nrezvani** [comment]
We can also export the dashboard and visualizations as a json file: [ctia_statistics_dashboard.json.zip](https://github.com/threatgrid/ctia/files/287361/ctia_statistics_dashboard.json.zip)

**Comment by nrezvani** [comment]
Created a new dashboard using the new data with index ctia*: [CTIA statistics dashboard](http://alpha.ctia.threatgrid.com/app/kibana#/dashboard/CTIA-Statistics)

**Comment by sashank** [comment]
How to access these dashboards ? we worked on some interesting time line views to illustrate progression of intrusion kill chains , would like to contribute them here
