### ISSUE TITLE
Output configuration on launch

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#316]
In order to ease ops and debugging, at CTIA launch we should output:

- [ ] Configuration sources that are detected/used
- [ ] The properties map with its configured values
- [ ] CTIA release version

**Comment by polygloton** [comment]
Could we log it instead?

**Comment by gbuisson** [comment]
yes, we seem to use tools.logging for the events file appender, any objection to use that for other matters?

**Comment by polygloton** [comment]
We should be using it a lot more than we are.
