### ISSUE TITLE
Add route for caching to check for updates

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#32]
We will use an E-Tag for each stored data structure for tracking 
- [ ] Stored models need an :etag field
- [ ] E-tag should be random UUID that gets changed for each update
- [ ] Route takes model ID and E-tag, returning true (?) if the Etag is invalid (if the model has changed)
- [ ] Do we want a separate :version field, which is a simple counter?
- [ ] E-tag is included in HTTP header for routes that GET a single model instance.

**Comment by yogsototh** [comment]
ETags are supported.
