### ISSUE TITLE
Multiple documents per sighting entity in ctia_sighting index

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#335]
Unlike judgement entities, when I post one sighting object to CTIA, it creates _two_ documents in the ctia_sightings index.  Is this correct behavior?

**Comment by gbuisson** [comment]
I believe that happens because sighting uses a nested datatype on :observables, which creates 2 documents, one for the sighting itself and another hidden doc for observables.

see: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/nested.html

**Comment by saintx** [comment]
That's what I suspected--thank you very much!
