### ISSUE TITLE
Handling schema upgrades

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#349]
I think we need the debutant release to be future proof when it comes to handling CTIM schema changes.

I've been thinking about the data migration workflow and here is a proposal:
- Each store (atom, SQL, ES) shall have an upgrade method
- For each implementation this method shall implement the workflow that best match the underlying data store
- Create a migration namespace that would define upgrade data transforms from one version to another.
- Create a CTIA task to launch upgrades (for all store or only some).

ES Specifics:
I think we can handle data migrations with no downtime using the official guide here:
https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html
- Make versioned indexes with aliases, use aliases for reads/writes rather than the index directly
- The upgrade process shall create a new versioned index and copy the transformed data
- When all documents from the previous index are migrated, change the alias so that it points to the new index.

We don't have to write all of this now, I think only the aliased Indexes is required if we want to ensure future migrations.

**Comment by saintx** [comment]
I believe I attempted at one point to configure a CTIA store to point to an index alias in ES, pointing at a new, empty index, and it could not correctly set up the mappings.  If memory serves, it needed to point at the actual index to set up the mappings, not the alias.

**Comment by gbuisson** [comment]
Yes, the mappings will be setup at index creation by CTIA.
