### ISSUE TITLE
Capture jetty standard out/error

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#364]
Either log it (preferably) or print it.  We must have lost this feature when we stopped using lein-ring.

One way to do this would be to add a custom middleware that catches exceptions and logs them before re-throwing them.

**Comment by craigbro** [comment]
We are capturing it, in /tmp/test.log  I think that's a bad place for it, but at least now I can actually debug test failures.

We should have our fixture modify this to write it to test.log in the directory.
