### ISSUE TITLE
Some entity fields should not be returned

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#367]
Such as :owner, :created, and :modified.

Maybe we could put all of these sort of keys under a :meta keyword in a nested map, or maybe we should just remove them all before sending responses.

**Comment by craigbro** [comment]
Hmm, I kinda like the :meta map part, since it means we can't accidently leak....

**Comment by gbuisson** [comment]
I think we should work on that now as other services need to work on precise fixtures from CTIM entities

**Comment by polygloton** [comment]
Don't use :meta keyword, just remove those fields individually.
