### ISSUE TITLE
A Verdict Redis Store

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#372]
Define a new Store that implements the IVerdictStore protocol.

**Comment by craigbro** [comment]
This will depend on the completion of converting verdicts to use TYPE:HASH(VALUE) as their identifier.  Check with craig and paula

**Comment by polygloton** [comment]
I think #363 will be important for this as well, as it will allow us to stand up redis and then back-fill it with verdicts, and we wouldn't need to worry about redis persistence.

**Comment by craigbro** [comment]
accidentla close
