### ISSUE TITLE
Create a SplitStore

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#373]
Create a SplitStore: A store that dispatches r/w requests on a configurable set of stores by route or set of routes.

**Comment by polygloton** [comment]
I think we should make a store that can compose multiple delegated stores together.  However, I don't think we should try to make a do-it-all store that is assembled with properties.  I think it should be configured in code, probably defined in a map.  We can give each "split store" its own namespace.  I believe that we won't need very many of these compound stores, and we should try to keep it simple.
