### ISSUE TITLE
Entity Update / Insert to prevent needless duplication

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#388]
In addition to Indicators, we will need mechanisms for preventing duplication of TTPs (and eventually Actors, Campaigns, Relationships, COAs, etc).

If a StoredTTP exists with the same title and source, then we should not create a new TTP, but rather update the existing one with new fields, and update the :end_time value within the :valid_time for the TTP.  It's unlikely that TTP titles will change, but if they do, we can create a new TTP and let the old one expire.

We should examine the possible use cases to figure out the correct way to do these:
- New TTP has no corresponding Stored TTP (obviously, post the new one)
- New TTP is absolutely identical to Stored TTP (run importer on same data twice, no-op?)
- New TTP is identical to Stored TTP except for `:valid_time`
- New TTP has additional fields that are missing in Stored TTP
- New TTP changes/removes fields from the Stored TTP

Question: Should certain updates always prompt creation of new TTPs?  For example, if we are changing the TLP from "green" to "amber" for a given TTP, should we immediately expire the "green" one and create a new "amber" one, in order to preserve history for purposes of auditing?  It might be good to be able to see that certain things have changed historically, rather than rewriting history.

**Comment by saintx** [comment]
If we did choose to "expire and post" on certain types of updates, we could also make use of the "related TTPs" field, in order to, for lack of better terms, create a version chain.  You could see that a TTP was replaced by another TTP with the same title and source, which itself was later replaced by a third TTP.  Just a thought--it really comes down to the use case and whether we're abusing the model for purposes of version control.  I'm not really sure what our vision is for that.

**Comment by craigbro** [comment]
We are using an external_id field in entities, which allows external system to encode a unique identifier and thus avoid dupes.
