### ISSUE TITLE
HTML source in Swagger API docs

### ISSUE THREAD

**Issue by folbricht** [threatgrid/ctia#424]
Not sure if that's specific to my instance, but I'm getting HTML source when looking at the `Model` under any endpoint.
![screen shot 2016-10-04 at 10 35 07 pm](https://cloud.githubusercontent.com/assets/3505107/19125288/c123d340-8af3-11e6-998a-20846040e135.png)

**Comment by gbuisson** [comment]
I think this is an issue from compojure-api since 1.1.7, I filed an issue:

https://github.com/metosin/compojure-api/issues/252
