### ISSUE TITLE
external_id in /ctia/sightings should be wrapped in { .. }

### ISSUE THREAD

**Issue by folbricht** [threatgrid/ctia#425]
![screen shot 2016-10-04 at 10 35 07 pm](https://cloud.githubusercontent.com/assets/3505107/19125403/20ac26f0-8af4-11e6-90ac-5199ae7f8f62.png)

**Comment by gbuisson** [comment]
Actually not, this route is supposed to be queried this way:
`GET /ctia/sighting/external_id?external_id=<an_external_id>`

If we do otherwise then the HTTP router may get confused and we may conflict with the sighting by Id route:
`GET /ctia/sighting/{id}`

**Comment by craigbro** [comment]
Did you actually experience router confusion?  This seems to be a very tractable problem for the router, since /external_id/ is a fixed value, and is delimited and seperate from the "/".

**Comment by gbuisson** [comment]
I don't remember well, I need to try again, however I think we settled on `/external_id`to make the route explicit.

**Comment by polygloton** [comment]
There is a merged PR, and this issue got closed and then reopened.  @gbuisson Can you please common on the current status of this issue?

**Comment by gbuisson** [comment]
I reopened it as @folbricht created the issue as a bug I think it needs to be validated by QA

**Comment by polygloton** [comment]
Good idea.  We need a label for that.

**Comment by polygloton** [comment]
@folbricht Please review this issue.

**Comment by folbricht** [comment]
Looks better now. Though I find the name `external_id` a bit confusing, especially since it's not unique. @gbuisson suggested perhaps changing that to `tags` instead and I agree.
