### ISSUE TITLE
Bulk GET API improvements

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#472]
## Context

We need an endpoint to fetch multiple entities from references using a single HTTP call.
The purpose of these changes is essentially to ease the work on CTIA-UI and make it easier to use from a frontend development perspective as well as improve performance when you need to fetch multiple entities from a Reference list.

The Bulk GET route already exists but needs improvements:

1. The accepted `Reference`format currently is a "short URI", we need to change that so it accepts "full URIs".

2. since it's a GET HTTP route, The query is passed as an URI query parameter, thus we may hit the URI max length limit on some browsers.

3. splitting the query/response schemas into entity types might be troublesome for the client, if this is a legit issue, we might also want to simplify that.

## Proposal

1. Fix the route and make it so that it accepts only "long URIs"

2. Switch the route to `POST /bulk/fetch` and use the request body to provide the query as JSON, this is not elegant but would ensure we don't hit a browser limit, another issue is that we cannot proxy cache it.

3. I'm not convinced that grouping the request/responses by entity is troublesome for a client but if we really need to do that then either change the route, or duplicate it so the request schema would be: 

```clojure
[URI]
```
and the output schema would be:

```clojure
{URI :- Any}
```

Note that the Bulk GET route should still not retrieve entities hosted on a foreign CTIA instance.

**Comment by polygloton** [comment]
Here are some questions meant to start discussion:

1. What do we do if the user submits foreign IDs?
2. If it only supports local IDs, why not keep using short IDs?
3. Why not retrieve remote references?

**Comment by gbuisson** [comment]
Here are my thoughts:

1. If the user submits foreign IDs then I think the handler should either ignore those or throw.
2. we shouldn't use short IDs as they are not meant to exist at all I think, the fact that we're constantly wondering about that makes me believe that we need to rethink it.
on the frontend side, not having to manipulate the urls to extract the id is easier.
3. It's a defensive approach, having a CTIA instance calling others is a recipe for cascading network failures, that being said we could protect the handler using a circuit breaker if we really want that.
