### ISSUE TITLE
Confusing dependencies warning

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#475]
~/dev/ctia$ lein uberjar
Possibly confusing dependencies found:
[perforate "0.3.4"] -> [org.clojure/clojure "1.4.0"]
 overrides
[jonase/eastwood "0.2.3"] -> [org.clojure/clojure "1.5.1"]

Consider using these exclusions:
[jonase/eastwood "0.2.3" :exclusions [org.clojure/clojure]]

**Comment by polygloton** [comment]
Both of these should exclude clojure, I think.

**Comment by yogsototh** [comment]
I can't reproduce these message locally.

Do you still have them when you remove your `~/.lein/profiles.clj`?

**Comment by polygloton** [comment]
I also don't see these warnings.

**Comment by gbuisson** [comment]
I'm pretty sure this happens only if you have added some projects on your lein profile
