### ISSUE TITLE
Setup CORS support

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#482]
Setup CORS Access Control to allow CTIA-UI from a different domain.

- [x] add a middleware that sets the correct headers
- [x] make the allowed origins configurable
- [x] make the allowed methods configurable
- [x] set the defaults origins to localhost for easy hacking

https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS

**Comment by oakmac** [comment]
Good timing on this. I was working to set up a simple passthru proxy for ctia-ui development.

I will halt that effort for now.
