### ISSUE TITLE
Judgements endpoint for the UI

### ISSUE THREAD

**Issue by oakmac** [threatgrid/ctia#486]
This may be a subset of [Issue #472] and is related to discussions held in [Issue #471].

I thought it might be useful to describe "my perfect Judgements endpoint from a UI perspective". Something along the lines of:

`GET /api/judgements` or `GET /api/ui/judgements`

With query parameters:

- `include-indicators=true` - "injects" the full indicator entity into the indicators array as opposed to just providing the Indicator ID (see note below about "local" vs "remote" indicators)
- `sort-by=<fieldname>` - sorts on the specified fieldname
- `sort-dir=<asc or desc>` - sort direction
- `max-results=<number>` - maximum number of results to return in a single response
- `start-idx=<number>` - starting index of results to return
- `end-idx=<number>` - ending index of results to return
- `filter=???` - filter the results (see note below)

It's worth noting that this endpoint is 100% biased towards what the UI needs, specifically for the table described in [ctia-ui issue #2]. It does not take into account backend complexity, REST purity, GraphQL flexibility, etc.

re: "local" vs "remote" Indicators. I understand it may not be feasible to fetch Indicators on remote CTIA instances in all cases. Also - even in cases where that is possible - it can add significant time to return a list of Judgements with all Indicators fetched. In this situation I think the best thing to do is show the user the local Indicators immediately (ie: show them what we can show them immediately) and then let them fetch the remote ones through additional action if they desire. In the case of the Judgements table, we can wait until the user clicks to expand the row and then trigger the load for the additional Indicators.

re: filters. I don't 100% know how filters should work at this time. There is still some UX work to be done around what how filters work for the user that likely has implications for what the API would expose. I know there has been discussion (and a working implementation) around allowing a raw ElasticSearch query string for this purpose.

[Issue #471]:https://github.com/threatgrid/ctia/issues/471
[Issue #472]:https://github.com/threatgrid/ctia/issues/472
[ctia-ui issue #2]:https://github.com/threatgrid/ctia-ui/issues/2

**Comment by craigbro** [comment]
Use the graphql endpoint
