### ISSUE TITLE
Remove references and use only Relationships

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#491]
In support of #488.  Related to #471 and threatgrid/ctim#107.  Do not target master for merging related PR(s). Target branch ctim-release-4 instead.

**Comment by polygloton** [comment]
@craigbro After we remove references, do we need to change any of the sightings logic?  Currently a sighting needs either a list of indicators, or an observable, and we enforce that in the API.  In the schema, both are optional.  Without a list of indicators on the sighting, we can't enforce it when the sighting is created.

**Comment by craigbro** [comment]
If you can't enforce it, you can't enforce it...

**Comment by polygloton** [comment]
I think that is the case.
