### ISSUE TITLE
HTTP 500 errors caused by no data?

### ISSUE THREAD

**Issue by oakmac** [threatgrid/ctia#506]
- https://tenzin-beta.amp.cisco.com/ctia/actor/search?query=*
- https://tenzin-beta.amp.cisco.com/ctia/campaign/search?query=*
- https://tenzin-beta.amp.cisco.com/ctia/coa/search?query=*
- https://tenzin-beta.amp.cisco.com/ctia/incident/search?query=*

The above URLs result in a HTTP 500 error and the following response:
```
{"type":"unknown-exception","class":"clojure.lang.ExceptionInfo"}
```

@gbuisson mentioned that he might know the source of the issue.

**Comment by gbuisson** [comment]
Indeed that happens when no document for a given entity exists, the current behavior is that the indexes are lazily created, I'm going to change that with my next PR, I temporarily fixed your issue just creating some documents for now.

**Comment by gbuisson** [comment]
This should be fixed with the ES5 upgrade

**Comment by polygloton** [comment]
@oakmac Please confirm this is fixed and close the issue.
