### ISSUE TITLE
Better HTTP 400 errors?

### ISSUE THREAD

**Issue by oakmac** [threatgrid/ctia#512]
I am attempting to create a new Judgement by POSTing to the `ctia/judgement` endpoint.

I get the following HTTP 400 error from the JSON body I am sending:
```
{"errors":"(not (map? nil))"}
```

While I suspect that the 400 result is accurate (ie: client error, sending the wrong Judgement format), this particular error is not super helpful in explaining why the request failed.

As an example, consider if the following was returned:
```
{"errors":"Missing required key 'disposition'. New Judgements must contain a disposition number of 1-5."}
```
Thoughts on improving error responses?

**Comment by gbuisson** [comment]
We could "explain" the exceptions to the user.
for that we just need to hack the compojure-api exception handlers and wrap the schema errors with something like this:

https://github.com/cddr/integrity/blob/master/test/integrity/human_test.clj
