### ISSUE TITLE
Logout button should have feedback

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#521]
When a user logs out, they should be told they have logged out.  So we need a logout screen wireframe.

**Comment by pxninja** [comment]
![logout](https://cloud.githubusercontent.com/assets/17751642/22800563/58d69c74-eecf-11e6-8ce4-4794fafa02e1.png)

**Comment by pxninja** [comment]
Most modern web-apps instantly log the user out and return them to the login screen. If this is not desired (or feasible) functionality, I would recommend a simple "you've logged out" screen with the option to log back in.
