### ISSUE TITLE
Server error when looking up expired verdicts

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#530]

**Comment by polygloton** [comment]
This definitely a real thing (it is happening on Tenzin), but I have yet to reproduce it in a test locally.  Indeed, it is even [tested](https://github.com/threatgrid/ctia/blob/master/test/ctia/http/routes/observable/verdict_test.clj#L182-L262) already.

I need the stacktrace from tenzin if possible.  Here is a screen shot if of it happening.

![screen shot 2017-02-23 at 5 40 25 pm](https://cloud.githubusercontent.com/assets/368005/23286922/693d0050-f9ef-11e6-91de-f3e3efa32b89.png)

**Comment by gbuisson** [comment]
I neither could reproduce it locally, let's wait for the stacktrace

**Comment by polygloton** [comment]
Alex looked on the server and found that we are not logging the stracktrace.

I think I've seen this before with "unknown-exception" errors:

```sh
% curl -X GET --header 'Accept: application/json' --header 'api_key: 123' 'https://tenzin-beta.amp.cisco.com/ctia/domain/getmyip.org/verdict'
{"type":"unknown-exception","class":"java.lang.NullPointerException"}%
```

This is the only log: 

```
128.107.241.183 - - [24/Feb/2017:19:17:32 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
128.107.241.183 - - [24/Feb/2017:19:17:32 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
128.107.241.183 - - [24/Feb/2017:19:17:33 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
128.107.241.183 - - [24/Feb/2017:19:17:33 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
128.107.241.183 - - [24/Feb/2017:19:17:33 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
128.107.241.183 - - [24/Feb/2017:19:19:23 +0000] "GET /ctia/domain/getmyip.org/verdict HTTP/1.1" 500 69 "https://tenzin-beta.amp.cisco.com/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

I think that the next step should be for me to jack-in to the CTIA instance on the head node and troubleshoot.  This will require turning on the nrepl service (reconfiguring and restarting CTIA on the head node) and created an SSH tunnel to the server so that I can access the port.  Since this isn't blocking the MVP, I propose that we do this after we take a break.

Another possible test would be to configure my local CTIA to point to the tenzin ES servers.  I will investigate that first.

**Comment by polygloton** [comment]
Alex got a bit more from the log:

```
2017-02-24 19:15:28,658 ERROR (qtp1593088959-20 - /ctia/domain/getmyip.org/verdict) [ctia.http.exceptions] -
java.lang.NullPointerException
2017-02-24 19:17:18,433 INFO (qtp1593088959-22 - /ctia/domain/getmyip.org/verdict) [ctia.lib.es.document] - search-docs: {:sort {:created :desc}, :size 1, :from 0, :query {:bool {:filter [{:terms {observable.type (domain)}} {:terms {observable.value (getmyip.org)}}]}}}
2017-02-24 19:17:18,436 INFO (qtp1593088959-22 - /ctia/domain/getmyip.org/verdict) [ctia.lib.es.document] - search-docs: {:sort {:priority desc, :disposition asc, valid_time.start_time {:order asc, :mode min, :nested_filter {range {valid_time.start_time {lt now/d}}}}}, :size 100, :from 0, :query {:bool {:filter ({:range {valid_time.start_time {lt now/d}}} {:range {valid_time.end_time {gt now/d}}} {:term {observable.type domain}} {:term {observable.value getmyip.org}})}}}
2017-02-24 19:17:18,461 ERROR (qtp1593088959-22 - 
```

Still no trace.

**Comment by polygloton** [comment]
Need to make sure we log stack traces for unknown-exceptions before closing this issue.

**Comment by polygloton** [comment]
This is returning a 404 now, which is better than a 500 and is probably the correct response.

**Comment by polygloton** [comment]
I am seeing a variant of this bug when I first lookup vedicts that are not expired.  When I lookup the verdict for the first time I get a 500, but when I try it a second time it works.  I have been able to repeat this multiple times against the tenzin server.

![screen shot 2017-03-13 at 6 19 43 pm](https://cloud.githubusercontent.com/assets/368005/23881784/f80ed37a-0819-11e7-9f3b-c0eb0a8c8e82.png)

**Comment by polygloton** [comment]
Currently domain getmyip.org is giving a 500 no matter how many times I try it.

![screen shot 2017-03-13 at 8 26 42 pm](https://cloud.githubusercontent.com/assets/368005/23884699/8888358e-082b-11e7-8779-13d35622dc09.png)

**Comment by polygloton** [comment]
These are the (useless) log messages:

```
2017-03-14 03:25:37,421 INFO (qtp2033288893-23 - /ctia/domain/getmyip.org/verdict) [ctia.lib.es.document] - search-docs: {:sort {:created :desc}, :size 1, :from 0, :query {:bool {:filter [{:terms {observable.type (domain)}} {:terms {observable.value (getmyip.org)}}]}}}
2017-03-14 03:25:37,444 ERROR (qtp2033288893-23 - /ctia/domain/getmyip.org/verdict) [ctia.http.exceptions] - 
```

**Comment by polygloton** [comment]
My testing leads me to believe that the subsequent successful loading of verdicts is because the verdict gets created in the HTTP API handler.  The "getmyip.org" domain fails because it doesn't have any valid judgements (they are all expired).

I also noticed that we are not logging when the handler creates verdicts.  That is my fault.  :(

**Comment by polygloton** [comment]
I was able to reproduce the 500 error locally.  Need to clean up my test and fix the bug.
