### ISSUE TITLE
RelatedIdentity is vague; can we get rid of it?

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#54]
Both TTP and Actor have :identity fields that point to a RelatedIdentity type based on STIX:

http://stixproject.github.io/data-model/1.2/stixCommon/RelatedIdentityType

Which contains an IdentityType based on STIX:

http://stixproject.github.io/data-model/1.2/stixCommon/IdentityType

Which in turn contains more RelatedIdentityTypes.

I implemented this structure in common.clj using a generic Reference, and not in the circular way that STIX defines it.  My implementation may be wrong.  Furthermore, I can't help wondering if we can just get rid of the :identity fields completely.

Edit: need to reimplement :identity fields to match STIX.

**Comment by craigbro** [comment]
I think we should keep a representation of it that is captures it sufficiently to support import/export.
