### ISSUE TITLE
Disable verdict store hook and read mechanism if no verdict-store configured

### ISSUE THREAD

**Issue by craigbro** [threatgrid/ctia#545]
The current verdict store is highly suboptimal:

1. It writes a verdict obejct for every judgement
2. when doing verdict lookups, if basically does the same operation as we would be doing on the judgement store, it does a sorted search limited to 1....

If no verdict-store is configured, and that should be the default....  we should not enable the hook or the component of the verdict handler that uses the verdict-store...

**Comment by craigbro** [comment]
Hit me up on hipchat if you want to discuss this more.

**Comment by polygloton** [comment]
Should we implement this (and #544) or just get rid of the verdict store completely?

**Comment by polygloton** [comment]
Obsoleted by #546
