### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by msprunck** [threatgrid/ctia#569]
Add a new authentication service that supports JWT tokens.

This authentication service should:

- Implement the `IAuth` protocol
- Verify the JWT token validity with the public key.
- Verify the JWT token validity with the public key.
- Return an identity (`IIdentity`) if the token is valid and the [denied identity](https://github.com/threatgrid/ctia/blob/master/src/ctia/auth.clj#L97) otherwise. if the token is valid and the [denied identity](https://github.com/threatgrid/ctia/blob/master/src/ctia/auth.clj#L97) otherwise.
- Based on a configurable property in the JWT payload (ex: `{admin: true}`), the user could be identified as an admin with write capabilities or simple user with read only capabilities.

**Comment by yogsototh** [comment]
Done.
