### ISSUE TITLE
CTIA bundle API endpoint

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#629]
CTIA supports a bundle API endpoint, which allows users with the correct permissions to POST a CTIM [bundle object](https://github.com/threatgrid/ctim/blob/master/src/ctim/schemas/bundle.cljc).

## Key Results

- [x] By posting a bundle in this way, CTIA performs a "graph merge" on the input bundle.
- [x] The ability to post bundles must be controlled via permissions, while we test this feature, and updates to the deployment configuration should be submitted. This is an experimental beta feature not ready to be enabled for all users by default.
- [x] Objects in the bundle may use transient UUIDs, which CTIA converts to real UUIDs before adding them to storage. (This relates to [Bug #610: Transient IDs should not be stored.](https://github.com/threatgrid/ctia/issues/610))
- [x] The response of the bundle API endpoint contains a map of the transient UUIDs to the real UUIDs along with a brief status message for each item in the bundle. Status messages indicate whether a new object was created, an existing object was updated, or the system failed to store the object.

**Comment by msprunck** [comment]
The bundle format is validated by Compojure API with the body schema specified in the route. When an entity has an invalid format in the bundle, the entire import is considered invalid. Is this behaviour acceptable?

**Comment by msprunck** [comment]
[3:42 PM] Craig Brozefsky: I actually think that input validation should happen at submission time

**Comment by msprunck** [comment]
When a bundle is submitted, we are going to search for existing entities based on external_ids to know if an entity has to be created or updated. Does the same logic apply to Relationships?

**Comment by craigbro** [comment]
Format validation is correct and should be done at submission time.  I think it's perfectly valid for us to enforce "well-formedness" at submission time.  Reject the whole bundle if it's not well-formed -- it doesn't match the input schema.

Yes, a Relationship is just like any other entity.

**Comment by hshahman** [comment]
Verified in rel-20180312 v0.2
