### ISSUE TITLE
Bundle import only matches on all external IDs

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#651]
The filter function `{:external_ids external-ids}` used at https://github.com/threatgrid/ctia/blob/master/src/ctia/http/routes/bundle.clj#L142 will only match an object that has ALL of the same external IDs as the ones supplied in the entity, rather than matching if the stored object has any of the same XIDs.

For example, if I create an entity with `:external_ids ["prefix-foo"]`, and import it, and there already exists an object in storage with `:external_ids ["prefix-foo" "prefix-bar"]`, this filter function will not match, and the bundle importer will create a duplicate.

Similarly, if I attempt to import an entity with `:external_ids ["prefix-a" "prefix-b" "prefix-c"]`, and there is one in the store with `:external_ids ["prefix-c" "prefix-d" "prefix-e"]`, this filter function will not match, and the bundle importer will create a duplicate.

This means I cannot add a new external ID to an existing object in order to take advantage of the bundle import API endpoint for future duplication prevention.  I have to remove the historical external ID, or create an entire new object with only the new XID.

Is this a bug?  It definitely seems like one but I'll let you guys decide.

**Comment by saintx** [comment]
Answered this through testing.  If I submit an object with `:external-ids ["hydrant-a" "hydrant-b"]` and then another with `:external-ids ["hydrant-a"]`, it will not create a duplicate.

If I submit them in reverse order, it does create a duplicate, instead of updating the original.

**Comment by hshahman** [comment]
Verified in rel-20180312 v0.2
