### ISSUE TITLE
Disable Event Store :entity indexing

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#660]
Alter the mapping to disable indexing on that field, as it makes the index hit the max fields limit.

Propose the following changes:
 - [ ] dynamic: false
 - [ ] remove dynamic_templates
 - [ ] map entitty.id, entity.type, entity.source to token

**Comment by saintx** [comment]
The result of hitting this index limit is that REST API calls (such as PUT requests) that require creating events are yielding HTTP 500 errors of `"type":"unknown-exception"`, even if they are successful.

**Comment by gbuisson** [comment]
If the update passes while the event fails to be created, this is another major issue IMO as we explicitely required the hook to pass for any change to take effect on the store, we kept the hooks firing and the store access sequential for this reason, sacrificing performance.

**Comment by hshahman** [comment]
No QA required.
