### ISSUE TITLE
Cannot update :end_time of indicators

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#666]
The PUT `/ctia/indicator/{id}` route returns an HTTP 200 status code, but does not actually update the `:valid_time :end_time` of the indicator.  Subsequent GETs will show the object has not changed, despite the 200 response status on the update request.

I was able to successfully update the `:external_ids` of indicators.

**Comment by msprunck** [comment]
The [`default-realize-fn`](https://github.com/threatgrid/ctia/blob/master/src/ctia/domain/entities.clj#L103) does not allow the update of the `:valid_time` property.

**Comment by saintx** [comment]
Interesting.  In that case, this isn't a bug, but a design choice that might need to be reconsidered.  I need to either be able to invalidate or delete the duplicate indicators, so that client code doesn't accidentally map relationships to them in the future.

**Comment by saintx** [comment]
This should be addressed by the feature requests in #667

**Comment by hshahman** [comment]
Fixed by https://github.com/threatgrid/ctia/pull/670

**Comment by hshahman** [comment]
Verified in rel-20180314 v0.2
