### ISSUE TITLE
A better way to check an instance version

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#671]
It is sometime hard to quickly figure out versions of our deployed instances,
we often need to know if the updates have been applied, and if the config is up to date.
This can be a pain point especially when using load balancing strategies

here are some suggestions:

- Augment the /version route with a hash of the ctia.properties file
- perhaps also add this data as custom response headers.

**Comment by saintx** [comment]
Package updates are listed at https://github.com/threatgrid/iroh/wiki/Dashboard-Locations

**Comment by gbuisson** [comment]
That's great but I still believe having the properties hash and put them on the headers would be handy.

**Comment by saintx** [comment]
We could very easily add the hash of the properties file to that dashboard.  But, it seems like what you are going to need to do is log into each of the head nodes to get the hash of the properties file, and then compare it to the headers.  How is that faster?  I'm just a bit confused about that.

**Comment by gbuisson** [comment]
for QA: any http call to CTIA/Private CTIA will return new header data:

- X-Ctim-Version: the current ctim version used by the CTIA Server
- X-Ctia-Version: the current ctia version
- X-Ctia-Config: a hash of the current properties being used

**Comment by hshahman** [comment]
Verified in rel-v0.3
