### ISSUE TITLE
Error: "missing-required-key" on optional map type

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#735]
I'm getting the error message: `"modes_of_introduction":[{"note":"missing-required-key"},{"note":"missing-required-key"}]` when trying to import a Weakness in local CTIA (master branch).

However, `note` is not a required key in the Weakness schema's `ModeOfIntroduction` map type: https://github.com/threatgrid/ctim/blob/18f5876bbd60b6496dd6341c6a1e6b836d3826cb/src/ctim/schemas/weakness.cljc#L21-L28

**Comment by gbuisson** [comment]
In Flanders when you define a map entry it is set as required by default: 

https://github.com/threatgrid/flanders/blob/master/src/flanders/core.cljc#L18

Thus the `required?` here are superfluous, see the ModeOfIntroduction Object definition here: 

https://github.com/threatgrid/ctim/blob/18f5876bbd60b6496dd6341c6a1e6b836d3826cb/doc/structures/weakness.md#map8

So the code here works as designed, however the schema definition is incorrect and needs to be changed on CTIM, reopening the issue there and closing this one.
