### ISSUE TITLE
Elasticsearch docker image error

### ISSUE THREAD

**Issue by sokoban** [threatgrid/ctia#768]
I tried to start dev ENV, but elasticsearch 5.1 was not started.
so i tried other setting, it is working now.
Please verify docker setting.

before
  elasticsearch-dev:
    image: elasticsearch:5.1
    environment:
      - cluster.name=elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

after
  elasticsearch-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    environment:
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"

 Thank you

**Comment by gbuisson** [comment]
Did you notice anything meaningful in ES logs?
What's your setup? are you trying to run it on a Mac or a Linux system?

Many thanks.

**Comment by saintx** [comment]
It's very likely that you need to set your VM max_map_count for Elasticsearch, as noted in the README.md for that container.

## Linux Host Configuration

If your docker host OS is Linux, Elasticsearch 5x bootstrap checks the maximum map count configuration, tune it accordingly with `sudo sysctl -w vm.max_map_count=262144`
